export const Questions = [
    
    {
        prompt: "Who was the first President of the United States?",
        optionA: "George Washington",
        optionB: "Thomas Jefferson",
        optionC: "John Adams",
        optionD: "Benjamin Franklin",
        answer: "A",
    },
    {
        prompt: "Who is on the 100 dollar bill?",
        optionA: "George Washington",
        optionB: "Thomas Jefferson",
        optionC: "John Adams",
        optionD: "Benjamin Franklin",
        answer: "D",
    },
    {
        prompt: "What State is Purdue University Located?",
        optionA: "Indiana",
        optionB: "Michigan",
        optionC: "California",
        optionD: "Maine",
        answer: "A", 
    },
    {
        prompt: "Where do avocados originate from?",
        optionA: "Columbia",
        optionB: "Peru",
        optionC: "Mexico",
        optionD: "China",
        answer: "C", 
    },
    {
        prompt: "What Continent is Poland located?",
        optionA: "Asia",
        optionB: "Europe",
        optionC: "Australia",
        optionD: "South America",
        answer: "B", 
    },
    {
        prompt: "What is 12 X 12 + 4 / 2 ?",
        optionA: "140",
        optionB: "578",
        optionC: "168",
        optionD: "146",
        answer: "D", 
    },
    {
        prompt: "How many Oceans are there?",
        optionA: "2",
        optionB: "3",
        optionC: "4",
        optionD: "5",
        answer: "C", 
    },
    {
        prompt: "What Quaterback has the most superbowl wins",
        optionA: "Peyton Manning",
        optionB: "Joe Montana",
        optionC: "Patrick Mahomes",
        optionD: "Tom Brady",
        answer: "D", 
    },
    {
        prompt: "What is Califonia's State Animal?",
        optionA: "Grizzly Bear",
        optionB: "Rattle Snake",
        optionC: "Eagle",
        optionD: "Cougar",
        answer: "A", 
    },
    {
        prompt: "What is the largest state in the US",
        optionA: "Texas",
        optionB: "Alaska",
        optionC: "California",
        optionD: "Montana",
        answer: "B", 
    }
    
];